GlobalSite/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GlobalSite.Models
{
    public class Album
    {
        [Display(Name = "Пин код")]
        public string Id { get; set; }
        [Display(Name = "Название")]
        public string Name { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Required]
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public virtual ICollection<Photo> Photos { get; set; }
        public Album()
        {
            Photos = new List<Photo>();
        }
    }
}

GlobalSite/Controllers/AlbumController.cs
using GlobalSite.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace GlobalSite.Controllers
{
    public class AlbumController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        #region GetUser
        //для получения пользователя
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AlbumController()
        {
        }

        public AlbumController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        #endregion

        // получить конкретный альбом клиенту (незарегестрированному пользователю)
        public ActionResult Index(string id, int? page)
        {
            Album album = db.Albums.Find(id);
            if (album != null)
            {
                int pageSize = 3;
                int pageNumber = (page ?? 1);
                return View(album.Photos.ToPagedList(pageNumber, pageSize));
            }
            else return HttpNotFound();
        }

        #region CRUD_Album
        // Частичное представление "Список альбомов"
        [HttpGet]
        [Authorize]
        public ActionResult ListAlbum()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());

            if (user != null)
            {
                return PartialView("_ListAlbum", user.Albums);
            }
            return View();
        }

        // создать новый альбом
        [HttpGet]
        [Authorize]
        public ActionResult CreateAlbum()
        {
            Album album = new Album
            {
                UserId = User.Identity.GetUserId()
            };
            return View(album);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAlbum(Album album)
        {
            if (album != null)
            {
                if (album.Id.Length < 4)
                {
                    TempData["albumId"] = "Пин код должен содержать не менее четырех символов.";
                    return View();
                }
                foreach (var alId in db.Albums)
                {
                    if (alId.Id == album.Id)
                    {
                        TempData["albumId"] = "Этот пин код уже занят.";
                        return View();
                    }
                }
                db.Entry(album).State = EntityState.Modified;
                db.Albums.Add(album);
                db.SaveChanges();
            }
            return RedirectToAction("Dashboard", "Home");
        }

        // редактировать конкретный альбом
        [HttpGet]
        [Authorize]
        public ActionResult EditAlbum(string id)
        {
            Album album = db.Albums.Find(id);
            if (album != null)
            {
                ViewBag.PageName = "EditAlbum";
                return View(album);
            }
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult EditAlbum(Album album)
        {
            db.Entry(album).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Dashboard", "Home");
        }

        // удалить альбом
        [HttpGet]
        [Authorize]
        public ActionResult DeleteAlbum(string id)
        {
            Album album = db.Albums.Find(id);
            if (album != null)
            {
                return View(album);
            }
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("DeleteAlbum")]
        public ActionResult DeleteAl(string id)
        {
            Album album = db.Albums.Find(id);
            if (album != null)
            {
                db.Albums.Remove(album);
                db.SaveChanges();
            }
            return RedirectToAction("Dashboard", "Home");
        }

        #endregion

        #region Portfolio
        // получить портфолио
        [AllowAnonymous]
        public ActionResult Portfolio(string id)
        {
            if (id != null)
            {
                ApplicationUser user = db.Users.FirstOrDefault(u => u.LastName == id);
                if (user != null)
                {
                    ViewBag.facebook = user.Facebook;
                    ViewBag.instagram = user.Instagram;

                    Album album = user.Albums.FirstOrDefault(a => a.Name == "portfolio");
                    return View(album.Photos.ToList());
                }
            }
            return HttpNotFound();
        }
        #endregion

        #region CRUD_Photo
        // Частичное представление "Список фотографий"
        [Authorize]
        public ActionResult ListPhoto(string id)
        {
            Album album = db.Albums.Find(id);
            return PartialView("_ListPhoto", album.Photos.ToList());
        }

        // Добавление
        [HttpGet]
        [Authorize]
        public ActionResult AddPhoto()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AddPhoto(string id, Photo photo, HttpPostedFileBase uploadImage)
        {
            if (uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                // установка массива байтов
                photo.Image = imageData;
                // обязательная привязка к альбому
                photo.AlbumId = id;

                db.Photos.Add(photo);
                db.SaveChanges();
            }
            return RedirectToAction("EditAlbum", new { id });
        }

        // Редактирование
        [HttpGet]
        [Authorize]
        public ActionResult EditPhoto(int id)
        {
            Photo photo = db.Photos.Find(id);
            if (photo != null)
            {
                return View(photo);
            }
            return RedirectToAction("EditAlbum");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult EditPhoto(Photo photo)
        {
            db.Entry(photo).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("EditAlbum");
        }

        // Удаление
        [HttpGet]
        [Authorize]
        public ActionResult DeletePhoto(int id)
        {
            Photo photo = db.Photos.Find(id);
            if (photo != null)
            {
                return View(photo);
            }
            return RedirectToAction("EditAlbum");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [ActionName("DeletePhoto")]
        public ActionResult DeletePh(int id)
        {
            Photo photo = db.Photos.Find(id);

            if (photo != null)
            {
                db.Photos.Remove(photo);
                db.SaveChanges();
            }
            return RedirectToAction("EditAlbum");
        }
        #endregion
    }
}

GlobalSite/Views/Album/AddPhoto.cshtml
@model GlobalSite.Models.Photo

@{
	ViewBag.Title = "AddPhoto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить фотографию</h2>

@using (Html.BeginForm( "AddPhoto", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)
<fieldset>
	<legend>Добавить изображение</legend>

	<div class="editor-label">Название</div>
	<div class="editor-field">
		@Html.EditorFor(model => model.Name)
		@Html.ValidationMessageFor(model => model.Name)
	</div>

	<div class="editor-label">Файл изображения</div>
	<div class="editor-field">
		<input type="file" name="uploadImage" />
	</div>
	<div class="editor-label">Описание</div>
	<div class="editor-field">
		@Html.EditorFor(model => model.Description)
		@Html.ValidationMessageFor(model => model.Description)
	</div>
	<div class="editor-label">Цена</div>
	<div class="editor-field">
		@Html.EditorFor(model => model.Price)
		@Html.ValidationMessageFor(model => model.Price)
	</div>
	@Html.HiddenFor(model => model.AlbumId)
	@Html.HiddenFor(model => model.Album)
	<br />
	<p>
		<input type="submit" value="Добавить" />
	</p>
</fieldset>
}

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

GlobalSite/Views/Album/CreateAlbum.cshtml
@model GlobalSite.Models.Album

@{
	ViewBag.Title = "CreateAlbum";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание альбома</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<h4></h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
			<div>
				@if (TempData["albumId"] != null)
				{
					<p>@TempData["albumId"]</p>
				}
			</div>
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	@Html.HiddenFor(model => model.UserId)

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Создать" class="btn btn-default" />
		</div>
	</div>
	<br />
</div>
}

<div>
	@Html.ActionLink("Вернуться в панель управления", "Dashboard", "Home")
</div>

GlobalSite/Views/Album/DeleteAlbum.cshtml
@model GlobalSite.Models.Album

@{
    ViewBag.Title = "DeleteAlbum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление альбома</h2>

<h3>Вы действительно хотите удалить альбом @Html.DisplayFor(model => model.Name)?</h3>
<div>
	<h4></h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>
		<br />
		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>
	</dl>
	<br />
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Delete" class="btn btn-default" />
		</div>
	}
	<br />
	<br />
	@Html.ActionLink("Вернуться в панель управления", "Dashboard", "Home")
</div>

GlobalSite/Views/Album/DeletePhoto.cshtml
@model GlobalSite.Models.Photo

@{
	ViewBag.Title = "DeletePhoto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление фотографии</h2>

<h3>Вы уверенны что хотите удалить эту фотографию?</h3>
<div>
	<h4>Photo</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Price)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Price)
		</dd>

	</dl>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Удалить" class="btn btn-default" />
		</div>
		<br />
		@Html.ActionLink("Вернуться в редактирование альбома", "EditAlbum", new { id = Model.AlbumId })
	}
</div>

GlobalSite/Views/Album/EditAlbum.cshtml
@model GlobalSite.Models.Album

@{
	ViewBag.Title = "EditAlbum";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование альбома</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<h4>Альбом  @Html.DisplayFor(model => model.Name)</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.Id)

	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	@Html.HiddenFor(model => model.UserId)
	@Html.HiddenFor(model => model.User)

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Сохранить" class="btn btn-default" />
		</div>
	</div>
</div>
}
<br />
<br />
<h2>Фотографии в этом альбоме</h2>
@using (Html.BeginForm())
{
	<div class="form-horizontal">
		<div>
			@{Html.RenderAction("ListPhoto", "Album");}
		</div>
		<div class="btn btn-default">
			@Html.ActionLink("Добавить фотографию в альбом", "AddPhoto", new { id = Model.Id })
		</div>
	</div>
}
<br />
<div>
	@Html.ActionLink("Вернуться в панель управления", "Dashboard", "Home")
</div>

GlobalSite/Views/Album/EditPhoto.cshtml
@model GlobalSite.Models.Photo

@{
	ViewBag.Title = "EditPhoto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование фотографии</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Photo</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		@Html.HiddenFor(model => model.Image)

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
			</div>
		</div>

		@Html.HiddenFor(model => model.AlbumId)

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Сохранить" class="btn btn-default" />
			</div>
		</div>
	</div>
}

	<div>
		@Html.ActionLink("Вернуться в редактирование альбома", "EditAlbum", new { id = Model.AlbumId })
	</div>

GlobalSite/Views/Album/Index.cshtml
@model PagedList.IPagedList<GlobalSite.Models.Photo>
@using PagedList.Mvc;

@{
	ViewBag.Title = "";
	Layout = "~/Views/Shared/_CartLayout.cshtml";
}

@foreach (var item in Model)
{
	<div class="container" style="outline: 1px solid gray">
		<div class="row">

			<div class="col-xs-9">
				<h2>
					<strong>@Html.DisplayFor(modelItem => item.Name)</strong>
				</h2>
				<div style="margin-bottom:15px;">
					@Html.Raw("<img class='img-thumbnail' src=\"data:image/jpeg;base64,"
						+ Convert.ToBase64String(item.Image) + "\" />")
				</div>
			</div>
			<div class="col-xs-3">
				<h2 class="pull-right">
					<strong class="pull-right label label-primary">
						Цена: @Html.DisplayFor(modelItem => item.Price) грн.
					</strong>
				</h2>

				@using (Html.BeginForm("AddToCart", "Cart", new { id = item.Id }))
				{
					<div class="pull-right">
						@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
						<input type="submit" class="btn btn-success" value="Добавить в корзину" />
					</div>
				}
				<br />
				<h4>
					<span style="display:inline-block; margin-top: 5%">@Html.DisplayFor(modelItem => item.Description)</span>
				</h4>
			</div>
		</div>
	</div>
	<br />
}

<div class="text-center">
	Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount

	@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>

GlobalSite/Views/Album/Portfolio.cshtml
@model IEnumerable<GlobalSite.Models.Photo>

@{
	ViewBag.Title = "Portfolio";
	Layout = null;
}
<!DOCTYPE HTML>
<html>
<head>
	<title>Portfolio</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
	<link rel="stylesheet" href="@Url.Content("~/Content/PortfolioTemplate/")assets/css/main.css" />
	<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	<noscript><link rel="stylesheet" href="@Url.Content("~/Content/PortfolioTemplate/")assets/css/noscript.css" /></noscript>
</head>
<body class="is-loading-0 is-loading-1 is-loading-2">
	<!-- Main -->
	<div id="main">
		<!-- Header -->
		<header id="header">
			<div class="logohead">
				<img src="@Url.Content("~/Content/PortfolioTemplate/")images/logo.png" alt="" width="150">
			</div>
			<h1 class="text-center">Portfolio</h1>
			@*<p class="text-center">Just another Responsive Site by <a href="http://themewagon.com">Themewagon</a></p>*@

			<ul class="icons text-center">
				@if (ViewBag.facebook != null)
				{
					<li><a href=@ViewBag.facebook class="icon fa-facebook"><span class="label">Facebook</span></a></li>
				}
				@if (ViewBag.instagram != null)
				{
					<li><a href=@ViewBag.instagram class="icon fa-instagram"><span class="label">Instagram</span></a></li>
				}
			</ul>

		</header>
		<!-- Thumbnail -->
		<section id="thumbnails">

			@foreach (var item in Model)
			{
				<article>
					@Html.Raw("<a href=\"data:image/jpeg;base64," + Convert.ToBase64String(item.Image) + "\" class='thumbnail' >")@Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.Image) + "\" /></a>")
					<h2>@Html.DisplayFor(modelItem => item.Name)</h2>
					<p>@Html.DisplayFor(modelItem => item.Description)</p>
				</article>
			}

		</section>
		<!-- Footer -->
		<footer id="footer">
			<ul class="copyright text-center">
				<li>&copy; Click</li>
				<li>Design: <a href="http:themewagon.com">Themewagon</a></li>

			</ul>
		</footer>
	</div>
	<!-- Scripts -->
	<script src="@Url.Content("~/Content/PortfolioTemplate/")assets/js/jquery.min.js"></script>
	<script src="@Url.Content("~/Content/PortfolioTemplate/")assets/js/skel.min.js"></script>
	<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
	<script src="@Url.Content("~/Content/PortfolioTemplate/")assets/js/main.js"></script>
	<script type="text/javascript">
		$('.toggle').click(function () {
			$('.caption').toggle();
		})</script>
</body>
</html>

GlobalSite/Views/Album/_ListAlbum.cshtml
@model IEnumerable<GlobalSite.Models.Album>

<h2>Мои альбомы</h2>

<p>
	@Html.ActionLink("Создать новый альбом", "CreateAlbum")
</p>
<table class="table">

	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Id)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Description)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Id)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Name)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Description)
			</td>
			<td>
				@Html.ActionLink("Редактировать", "EditAlbum", new { id = item.Id }) |
				@Html.ActionLink("Удалить", "DeleteAlbum", new { id = item.Id })
			</td>
		</tr>
	}

</table>

GlobalSite/Views/Album/_ListPhoto.cshtml
@model IEnumerable<GlobalSite.Models.Photo>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
		<td>
			@Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
								+ Convert.ToBase64String(item.Image) + "\" />")
		</td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "EditPhoto", new { id=item.Id }) |
            @Html.ActionLink("Удалить", "DeletePhoto", new { id=item.Id })
        </td>
    </tr>
}

</table>